name: another-service
url: https://httpbin.org/anything
routes:
  - name: another-route
    paths:
      - /httpbin
    plugins:
      - name: request-transformer
        config:
          add:
            headers:
              - "x-added-header:example"