apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30081
  selector:
    app: kong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:local-dev
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/declarative/kong.yml
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
          ports:
            - containerPort: 8000
            - containerPort: 8001
          volumeMounts:
            - name: kong-config
              mountPath: /kong/declarative
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  labels:
    app: kong
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: example-service
        url: https://mockbin.org/request
        routes:
          - name: example-route
            paths:
              - /mock 