apiVersion: v1
data:
  kong.yml: |
    _format_version: '3.0'
    services:
      - name: another-service
        url: https://httpbin.org/anything
        routes:
          - name: another-route
            paths:
              - /httpbin
            plugins:
              - name: request-transformer
                config:
                  add:
                    headers:
                      - x-added-header:example
      - name: example-service
        url: https://mockbin.org/request
        routes:
          - name: example-route
            paths:
              - /mock
            plugins:
              - name: key-auth
                config:
                  key_names:
                    - apikey
    consumers:
      - username: demo-user
        keyauth_credentials:
          - key: demo-api-key
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kong-config
