apiVersion: v1
data:
  kong.yml: "_format_version: \"3.0\"\nservices:\n  - name: another-service\n    url:
    https://httpbin.org/anything\n    routes:\n      - name: another-route\n        paths:\n
    \         - /httpbin\n    plugins:\n      - name: request-transformer\n        config:\n
    \         add:\n            headers:\n              - \"x-added-header:example\"
    \  - name: example-service\n    url: https://mockbin.org/request\n    routes:\n
    \     - name: example-route\n        paths:\n          - /mock\n        plugins:\n
    \         - name: key-auth\n            config:\n              key_names:\n                -
    apikey \nconsumers:\n  - username: demo-user\n    keyauth_credentials:\n      -
    key: demo-api-key "
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kong-config
