apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30081
    - name: admin-gui
      port: 8002
      targetPort: 8002
      nodePort: 30082
  selector:
    app: kong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      initContainers:
        - name: kong-migrations
          image: kong:local-dev
          command: ['kong', 'migrations', 'bootstrap']
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: postgres
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PG_DATABASE
              value: kong
      containers:
        - name: kong
          image: kong:local-dev
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: postgres
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: kong
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PG_DATABASE
              value: kong
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_ADMIN_GUI_LISTEN
              value: 0.0.0.0:8002
            - name: KONG_ADMIN_GUI_URL
              value: http://localhost:8002
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /status
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 10
            successThreshold: 1
